name: dicom_to_jmix
version: 1
mappings:
  - type: map
    from: PatientID
    to: patient.identifier
  - type: transform
    from: StudyInstanceUID
    to: study.uid
    func:
    prefix:
    urn:
    dicom:
  - type: const
    to: jmix.meta.version
    value: "1.0"
  - type: conditional
    from: Modality
    to: study.modality
    condition: exists
