[package]
name = "custom_endpoint"
version = "0.1.0"
edition = "2021"

[lib]
name = "custom_endpoint"
crate-type = ["cdylib"]

[dependencies]
axum = "0.8.4"
async-trait = "0.1.88"
serde_json = "1.0.140"
harmony = { path = "../.." }