
# ------------------------
# Default pipeline
#-------------------------
[pipelines.default]
description = "Basic passthru test"     # Optional
networks = ["default"]                  # Optional, but pipeline should be skipped if empty or does not match, defaults to empty, should warn if empty
endpoints = ["basic_test"]              # Optional, but pipeline should be skipped if empty or does not match, defaults to empty, should warn if empty
middleware = [
    'middleware.passthru',
]                                       # Optional, defaults to empty, should warn if empty
backends = ["test_backend"]             # Optional, defaults to empty, should warn if empty

# ------------------------
# Middleware
#-------------------------

[middleware.passthru]
# This middleware has no configurable properties

# ------------------------
# Public endpoints
#-------------------------
[endpoints.basic_test]
type = "http"                           # Required
options = { path_prefix = "/test" }     # Required if type "http"

# ------------------------
# Backends
#-------------------------
[backends.test_backend]
type = "http"
targets = ["test_target"]

# ------------------------
# Targets
#-------------------------
[targets.test_target]
type = "http"
url = "http://localhost:8081/test"


# Built-in types (empty module means built-in)
[endpoint_types.http]
module = ""

[endpoint_types.fhir]
module = ""

# Custom types (specify module path)
[endpoint_types.custom_api]
module = "modules/custom_api"

[endpoint_types.legacy_soap]
module = "modules/soap_endpoint"

# Service types
[service_types.auth]
module = "modules/auth_service"

[service_types.rate_limiter]
module = ""  # Built-in service

