# Example configuration showing DICOM integration with the new DIMSE crate
# This demonstrates:
# - Backend usage (SCU): HTTP endpoint + DICOM backend triggers outbound DIMSE ops
# - Endpoint usage (SCP): DICOM endpoint accepts DICOM connections and forwards into the pipeline

[proxy]
id = "harmony-dimse-demo"
log_level = "debug"
store_dir = "./tmp/harmony"
pipelines_path = "examples"
transforms_path = "examples"

[network.default]
enable_wireguard = false
interface = "wg0"

[network.default.http]
bind_address = "0.0.0.0"
bind_port = 8080

# Pipeline showing DICOM backend usage (SCU)
[pipelines.dicom_backend_demo]
description = "Demo DICOM backend usage - HTTP request triggers DIMSE SCU operations"
networks = ["default"]
endpoints = ["http_to_dicom"]
middleware = []
backends = ["dicom_pacs"]

# Pipeline showing DICOM endpoint usage (SCP)
[pipelines.dicom_scp_demo]
description = "Demo DICOM endpoint (SCP) - accepts DICOM connections and runs the pipeline"
networks = ["default"]
endpoints = ["dicom_scp"]
middleware = []
backends = []

# HTTP endpoint that triggers DICOM backend operations
[endpoints.http_to_dicom]
service = "http"
options = { path_prefix = "/trigger-dicom" }

# DICOM endpoint (SCP). This accepts DICOM network connections (no HTTP routes)
[endpoints.dicom_scp]
service = "dicom"

[endpoints.dicom_scp.options]
local_aet = "HARMONY_SCP"
# bind_addr = "0.0.0.0"
# port = 11112

# DICOM backend for SCU operations
[backends.dicom_pacs]
service = "dicom"

[backends.dicom_pacs.options]
aet = "ORTHANC"
host = "localhost"
port = 4242
local_aet = "HARMONY_SCU"

# Optional: add backends/middleware to the dicom_scp_demo pipeline as needed to process inbound DIMSE

[logging]
log_to_file = true  
log_file_path = "./tmp/harmony_dimse_demo.log"