version: '3.8'

services:
  harmony:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./config:/etc/harmony:ro
      - ./tmp:/tmp/harmony
      - ./examples:/examples:ro
    environment:
      - RUST_LOG=harmony=debug
      # - RUNBEAM_ENCRYPTION_KEY=${RUNBEAM_ENCRYPTION_KEY}
      # - RUNBEAM_MACHINE_TOKEN=${RUNBEAM_MACHINE_TOKEN}
      # - RUNBEAM_PUSH_CONFIG_ON_STARTUP=true
      # - RUNBEAM_ACCEPT_INVALID_CERTS=true
