# FHIR to DICOM Translation Example Configuration
# Demonstrates HTTP to DICOM translation with middleware transformations

[proxy]
id = "harmony-fhir-to-dicom"
log_level = "debug"
pipelines_path = "pipelines"
transforms_path = "transforms"

# Network configuration
[network.http_net]
enable_wireguard = false
interface = "wg0"

[network.http_net.http]
bind_address = "127.0.0.1"
bind_port = 8082

# Logging
[logging]
log_to_file = true
log_file_path = "./tmp/harmony_fhir_to_dicom.log"

# Storage
[storage]
backend = "filesystem"

[storage.options]
path = "./tmp"

# Service types
[services.http]
module = ""

[services.dicom]
module = ""

# Middleware types
[middleware_types.basic_auth]
module = ""

[middleware_types.json_extractor]
module = ""
