# ------------------------
# Defines the proxy
#-------------------------
[proxy]
id = "harmony-test"
log_level = "debug"
store_dir = "/tmp/harmony"

# ------------------------
# Network
#-------------------------
[network.default]
enable_wireguard = false
interface = "wg0"

[network.default.http]
bind_address = "0.0.0.0"  # Listen on all interfaces
bind_port = 8080          # Use port 8080

# ------------------------
# Endpoint groups
#-------------------------
[groups.fhir_test]
description = "FHIR endpoints for testing"
networks = ["default"]
middleware = { endpoint = ["jwt_auth"], service = [], backend = []}
endpoints = ["fhir_test_endpoint_a", "fhir_test_endpoint_b"]
backends = ["test_fhir_backend"]

[groups.basic_text]
description = "Basic passthru test"
networks = ["default"]
endpoints = ["basic_test"]
middleware = [
    'middleware.basic_auth',
    'services.passthru',
    'middleware.transform',
    'services.passthru',
]
backends = ["test_jmix_backend"]

# ------------------------
# Middleware
#-------------------------
[middleware.jwt_auth]
public_key_path = "/path/to/test/public_key.pem"

[middleware.auth_sidecar]
token_path = "/tmp/test_token"
username = "test_user"
password = "test_password"

[middleware.fhir_dicom_transform]

# ------------------------
# Services
#-------------------------
[services.passthru_1]
type = "passthru"

[services.passthru_2]
type = "passthru"

# ------------------------
# Public endpoints
#-------------------------
[endpoints.basic_test_endpoint_a]
type = "http"
path_prefix = "/test-a"

[endpoints.fhir_test_endpoint_b]
type = "fhir"
path_prefix = "/fhir/test-b"

[endpoints.jmix_test_endpoint]
type = "jmix"
path_prefix = "/jmix/test"

# ------------------------
# Backends
#-------------------------
[backends.test_fhir_backend]
type = "passthru"
targets = ["test_fhir_target"]

[backends.test_jmix_backend]
type = "passthru"
targets = ["test_jmix_target"]

# ------------------------
# Targets
#-------------------------
[targets.test_fhir_target]
type = "fhir"
url = "http://localhost:8081/test/fhir"

[targets.test_jmix_target]
type = "jmix"
url = "http://localhost:8082/test/jmix"

# ------------------------
# Logging
#-------------------------
[logging]
log_to_file = true
log_file_path = "/tmp/harmony_test.log"