# ------------------------
# Basic configuration
#-------------------------
[proxy]
# The name of the proxy, required
id = "harmony"
# The log level. Defaults to 'error'
log_level = "debug"
# Directories are resolved relative to this config file's directory
pipelines_path = "pipelines"
transforms_path = "transforms"

# ------------------------
# Network
#
# Defines 0 or more network configurations.
#-------------------------
[network.default]
# Whether to enable wireguard connections on this network
enable_wireguard = false
interface = "wg0"

[network.default.http]
bind_address = "0.0.0.0"  # Listen on all interfaces
bind_port = 8080          # Use port 8080

# ------------------------
# Logging
#-------------------------
[logging]
log_to_file = true
log_file_path = "./tmp/harmony_test.log"

# ------------------------
# Storage
#
# Configurable storage backend for temporary files
#-------------------------
[storage]
backend = "filesystem"

[storage.options]
path = "./tmp"

# ------------------------
# Service types
#-------------------------
[services.http]
module=""

[services.fhir]
module=""

[services.dicom]
module=""

[services.echo]
module=""

[services.jmix]
module=""

[services.dicomweb]
module=""

# ------------------------
# Available middleware
#-------------------------
[middleware_types.jwtauth]
module=""

[middleware_types.auth]
module=""

[middleware_types.connect]
module=""

[middleware_types.json_extractor]
module=""

[middleware_types.passthru]
module=""

[middleware_types.transform]
module=""

# DICOMweb <-> DICOM bridge middleware
[middleware_types.dicomweb_to_dicom]
module=""

[middleware_types.dicom_to_dicomweb]
module=""

# JMIX builder middleware
[middleware_types.jmix_builder]
module=""

# Aliases
[middleware_types.json]
module=""

[middleware_types.dicomweb]
module=""
