
# ------------------------
# Defines the proxy
#-------------------------
[proxy]
id = "harmony-incoming"
log_level = "info"
store_dir = "/var/lib/jmix/studies"

# ------------------------
# Network
#-------------------------
[network.default]
enable_wireguard = true
interface = "wg0"

[network.default.http]
bind_address = "1.2.3.4"
bind_port = 8080

# ------------------------
# Endpoint groups
#-------------------------
[groups.fhir]
description = "FHIR endpoints exposed to external clients"
networks = ["default"]
middleware = { incoming = ["jwt_auth"], outgoing = [] }
endpoints = ["fhir_endpoint_a"]
backends = ["fhir"]

[groups.fhir_dicom]
description = "DICOM PACS systems exposing FHIR endpoints"
networks = ["default"]
middleware = { incoming = ["jwt_auth"], outgoing = [] }
endpoints = ["fhir_endpoint_b"]
backends = ["dicom_fhir"]

[groups.dicomweb_dicom]
description = "DICOM PACS systems exposing DICOMWeb endpoints"
networks = ["default"]
middleware = { incoming = ["jwt_auth"], outgoing = [] }
endpoints = ["dicomweb_endpoint"]
backends = ["dicom_dicomweb"]

[groups.jmix_dicom]
description = "DICOM PACS systems exposing JMIX endpoints"
networks = ["default"]
middleware = { incoming = ["jwt_auth"], outgoing = [] }
endpoints = ["jmix_endpoint"]
backends = ["dicom_jmix"]

# ------------------------
# Public endpoints
#-------------------------
[endpoints.fhir_endpoint_a]
type = "fhir"
path_prefix = "/fhir/endpoint-a"

[endpoints.fhir_endpoint_b]
type = "fhir"
path_prefix = "/fhir/endpoint-b"

[endpoints.dicomweb_endpoint]
type = "dicomweb"
path_prefix = "/dicomweb"

[endpoints.jmix_endpoint]
type = "jmix"
path_prefix = "/jmix/endpoint"

[endpoints.my_custom]
type = "custom"
handler_path = "/path/to/libmy_custom_endpoint.so"
group = "custom_group"
path_prefix = "/custom"

# ------------------------
# Backends
#-------------------------
[backends.passthru_fhir]
type = "passthru"
services = ["fhir_a"]

[backends.dicom_fhir]
type = "dicom_to_fhir"
services = ["pacs_a"]
aet = "HM_DICOM_A"
port = 104

[backends.dicom_dicomweb]
type = "dicom_to_dicomweb"
services = ["pacs_a"]
aet = "HM_DICOM_B"
port = 55555

[backends.dicom_jmix]
type = "dicom_to_jmix"
services = ["pacs_a"]
aet = "HM_DICOM_B"
port = 55556

[backends.dicom_harmony]
type = "dicom_to_harmony"
services = ["pacs_a"]
aet = "HARMONY"
port = 55557

# ------------------------
# Services
#-------------------------
[services.fhir_a]
type = "fhir"
url = "http://localhost:8081/fhir"

[services.pacs_a]
type = "dicom"
aet = "PACSCLINIC"
host = "127.0.0.1"
port = 104