# ------------------------
# Defines the proxy
#-------------------------
[proxy]
id = "harmony-outgoing"
log_level = "info"
store_dir = "/var/lib/harmony/studies"

# ------------------------
# Network
#-------------------------

[network.internal]
enable_wireguard = true
interface = "wg0"

[network.internal.http]
bind_address = "192.168.0.1"  # Listen on a local interface
bind_port = 8081

[[network.internal.peers]]
id = "jmix-hospital-b"
ip = "10.6.0.2"
public_key = "PUBKEY_HOSPITAL_B"

[[network.internal.peers]]
id = "jmix-lab-c"
ip = "10.6.0.3"
public_key = "PUBKEY_LAB_C"

# ------------------------
# Endpoint groups
#-------------------------

[groups.outgoing]
description = "DICOM PACS connecting to JMIX endpoints"
networks = ["network.internal"]
middleware = { incoming = [], outgoing = [] }
backends = ["endpoints.internal"]
peers = ["*"] # Allow any peers

# ------------------------
# Public endpoints
#-------------------------

# Endpoints are not required for outgoing conections

# ------------------------
# Backends
#-------------------------

[backends.dicom_harmony]
type = "dicom_to_harmony"
services = ["services.pacs_a"]
aet = "HARMONY"
port = 55557

# ------------------------
# Services
#-------------------------
[services.pacs_a]
type = "dicom"
aet = "PACSCLINIC"
host = "127.0.0.1"
port = 104
