[proxy]
id = "harmony-test"
log_level = "info"
store_dir = "/tmp/harmony"

[network.default]
enable_wireguard = false
interface = "wg0"

[network.default.http]
bind_address = "0.0.0.0"  # Listen on all interfaces
bind_port = 8080          # Use port 8080

[endpoints.test]
type = "basic"
path_prefix = "/test"

[backends.deadletter]
type = "deadletter"

[groups.test_group]
description = "A test group"
networks = ["default"]
middleware = { incoming = [], outgoing = [] }
endpoints = ["test"]
backends = ["deadletter"]

[logging]
log_to_file = true
log_file_path = "/tmp/harmony.log"