# ------------------------
# FHIR ImagingStudy Pipeline (Approach A: JOLT Transform)
# ------------------------
# Implements GET /ImagingStudy?patient={id} endpoint
# Converts DICOM C-FIND STUDY responses to FHIR ImagingStudy Bundle

[pipelines.imagingstudy_query]
description = "GET /ImagingStudy?patient={id}"
networks = ["default"]
endpoints = ["fhir_imagingstudy_ep"]
middleware = [
    "imagingstudy_filter",
    "query_to_target",
    "json_extractor",
    "fhir_dimse_meta",
    "fhir_to_dicom_transform",
    "enrich_jmix_urls",
    "dicom_to_fhir_transform"
]
backends = ["dicom_backend"]

# ------------------------
# Middleware
# ------------------------

[middleware.imagingstudy_filter]
type = "path_filter"
[middleware.imagingstudy_filter.options]
rules = ["/ImagingStudy"]

[middleware.query_to_target]
type = "metadata_transform"
[middleware.query_to_target.options]
spec_path = "query_to_target_details.json"
apply = "left"
fail_on_error = false
transform_target = "target_details"

[middleware.json_extractor]
type = "json_extractor"

[middleware.fhir_dimse_meta]
type = "metadata_transform"
[middleware.fhir_dimse_meta.options]
spec_path = "metadata_set_dimse_op.json"
apply = "left"
fail_on_error = true

[middleware.fhir_to_dicom_transform]
type = "transform"
[middleware.fhir_to_dicom_transform.options]
spec_path = "fhir_to_dicom_params.json"
apply = "left"  # Transform request to DICOM parameters
fail_on_error = false
inject_context = true  # Enable context injection for query params access

[middleware.enrich_jmix_urls]
type = "transform"
[middleware.enrich_jmix_urls.options]
spec_path = "enrich_with_jmix_urls.json"
apply = "right"  # Transform DICOM response to add JMIX URLs
fail_on_error = false
inject_context = true

[middleware.dicom_to_fhir_transform]
type = "transform"
[middleware.dicom_to_fhir_transform.options]
spec_path = "dicom_to_imagingstudy_simple.json"
apply = "right"  # Transform DICOM response to FHIR
fail_on_error = true
inject_context = true  # Enable context injection

# ------------------------
# Endpoints
# ------------------------

[endpoints.fhir_imagingstudy_ep]
service = "fhir"
[endpoints.fhir_imagingstudy_ep.options]
path_prefix = "/fhir"

# ------------------------
# Backends
# ------------------------

# Production DICOM backend
#[backends.dicom_backend]
#service = "dicom"
#[backends.dicom_backend.options]
#local_aet = "HARMONY_SCU"
#aet = "PACSCLINIC"
#host = "127.0.0.1"
#port = 104

# Alternative: Mock backend for testing
[backends.dicom_backend]
service = "mock_dicom"
