
# ------------------------
# This demonstrates a basic pipeline with no backend
# The echo endpoint just returns the original request.
#-------------------------
[pipelines.default]
description = "Basic passthru test"     # Optional
networks = ["external"]                 # Optional, but pipeline should be skipped if empty or does not match, defaults to empty, should warn if empty
endpoints = ["basic_test"]              # Optional, but pipeline should be skipped if empty or does not match, defaults to empty, should warn if empty
middleware = [
    "passthru",
]                                       # Optional, defaults to empty, should warn if empty
backends = ["test_backend"]             # Optional, defaults to empty, should warn if empty

# ------------------------
# Middleware
#-------------------------

[middleware.passthru]
type = "passthru"

# ------------------------
# Public endpoints
#-------------------------
[endpoints.basic_test]
service = "http"
[endpoints.basic_test.options]
path_prefix = "/test"

# ------------------------
# Backends
#-------------------------
[backends.test_backend]
service = "echo"
[backends.test_backend.options]
path_prefix = "/echo-back"

