# ------------------------
# Endpoint groups
#-------------------------
[pipelines.fhir]
description = "FHIR passthru test"
networks = ["external"]
endpoints = ["fhir_test"]
middleware = [
    "basic_auth",
    "json_extractor",
]
backends = ["fhir_backend"]

# ------------------------
# Middleware
#-------------------------

[middleware.passthru]
type = "passthru"

[middleware.basic_auth]
type = "basic_auth"
[middleware.basic_auth.options]
token_path = "./tmp/test_token"
username = "test_user"
password = "test_password"

[middleware.json_extractor]
type = "json_extractor"

# ------------------------
# Endpoints
#-------------------------
[endpoints.fhir_test]
service = "http"
[endpoints.fhir_test.options]
path_prefix = "/test"

# ------------------------
# Backends
#-------------------------
[backends.fhir_backend]
service = "echo"
[backends.fhir_backend.options]
path_prefix = "/fhir-back"
