# ------------------------
# High-Performance JMIX endpoint configuration
# This example shows how to configure default skip flags in the config file
#-------------------------
[pipelines.jmix_performance]
description = "High-performance JMIX API with default skip flags for large datasets"
networks = ["external"]
endpoints = ["jmix_api_performance"]
middleware = [
    "jmix_builder",
]
backends = ["dicom_pacs"]

# ------------------------
# Middleware
#-------------------------
[middleware.jmix_builder]
type = "jmix_builder"

# ------------------------
# High-Performance JMIX HTTP endpoint with default skip flags
# Routes:
#   GET  /jmix/api/jmix?studyInstanceUid=...     -> uses config defaults, can be overridden by query params
#   GET  /jmix/api/jmix/{id}                     -> download stored envelope (zip/gzip via Accept)
#   GET  /jmix/api/jmix/{id}/manifest            -> fetch stored manifest.json
#
# Configuration options:
#   skip_hashing: true/false (default: false) - Skip SHA256 hash computation for performance
#   skip_listing: true/false (default: false) - Skip DICOM files from files.json manifest
#   store_dir: path (optional) - Custom storage directory for JMIX envelopes
#-------------------------
[endpoints.jmix_api_performance]
service = "jmix"
[endpoints.jmix_api_performance.options]
path_prefix = "/jmix"
# Default performance optimizations - can be overridden by query parameters
skip_hashing = true   # Skip SHA256 hashing by default for faster processing
skip_listing = false  # Still include file listings by default for inventory

# Optional: custom storage directory
# store_dir = "./tmp/jmix-store-performance"

# ------------------------
# DICOM backend (remote PACS)
#-------------------------
[backends.dicom_pacs]
service = "dicom"
[backends.dicom_pacs.options]
aet = "ORTHANC"              # Remote AE (Orthanc)
host = "127.0.0.1"
port = 4242
local_aet = "HARMONY_SCU"    # Our AE title
incoming_store_port = 11112  # Port Orthanc will push C-STORE to
persistent_store_scp = true  # keep a persistent C-STORE SCP listening