# ------------------------
# Transform Middleware Example
#-------------------------
# ------------------------
# Pipeline with Transform
#-------------------------
[pipelines.transform_demo]
description = "Demonstrates JOLT transform middleware"
networks = ["default"]
endpoints = ["http_endpoint"]
middleware = [
    'middleware.json_extractor',
    'middleware.patient_transform',
]
backends = []

# ------------------------
# Middleware
#-------------------------
[middleware.json_extractor]
# Extracts JSON from request body

[middleware.patient_transform]
type = "transform"
[middleware.patient_transform.options]
spec_path = "examples/config/transforms/patient_to_fhir.json"
apply = "left"
fail_on_error = true

# ------------------------
# Endpoints
#-------------------------
[endpoints.http_endpoint]
service = "http"
[endpoints.http_endpoint.options]
path_prefix = "/transform"

