# ------------------------
# Transform Middleware Example
#-------------------------
# ------------------------
# Pipeline with Transform
#-------------------------
[pipelines.transform_demo]
description = "Demonstrates JOLT transform middleware"
networks = ["http_net"]
endpoints = ["http_endpoint"]
middleware = [
    "json_extractor",
    "patient_transform",
]
backends = []

# ------------------------
# Middleware
#-------------------------
[middleware.json_extractor]
type = "json_extractor"

[middleware.patient_transform]
type = "transform"
[middleware.patient_transform.options]
spec_path = "transforms/patient_to_fhir.json"
apply = "left"
fail_on_error = true

# ------------------------
# Endpoints
#-------------------------
[endpoints.http_endpoint]
service = "http"
[endpoints.http_endpoint.options]
path_prefix = "/transform"

