replicaCount: 1

serviceAccount:
  create: true
  name: ""

image:
  repository: aurabox/harmony
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  managementPort: 9090

config:
  # Path to mounted config file
  path: /etc/harmony/harmony-config.toml

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
