# ------------------------
# HTTP Backend Pipeline
# Demonstrates HTTP passthrough to external service
#-------------------------
[pipelines.http_proxy]
description = "HTTP proxy to external backend service"
networks = ["http_net"]
endpoints = ["proxy_endpoint"]
middleware = [
    "passthru",
]
backends = ["external_api"]

# ------------------------
# Middleware
#-------------------------
[middleware.passthru]
type = "passthru"

# ------------------------
# Public endpoints
#-------------------------
[endpoints.proxy_endpoint]
service = "http"
[endpoints.proxy_endpoint.options]
path_prefix = "/api"

# ------------------------
# Backends - External HTTP service
#-------------------------
[backends.external_api]
service = "http"
[backends.external_api.options]
base_url = "https://httpbin.org"