# ------------------------
# DICOMweb endpoint example
#-------------------------
[pipelines.dicomweb_demo]
description = "DICOMweb QIDO-RS and WADO-RS endpoint bridging to DIMSE via middleware"
networks = ["default"]
endpoints = ["dicomweb_endpoint"]
middleware = [
    'dicomweb_bridge',
]
backends = ["dicom_pacs"]

# ------------------------
# Endpoints
#-------------------------
[endpoints.dicomweb_endpoint]
service = "dicomweb"
[endpoints.dicomweb_endpoint.options]
path_prefix = "/dicomweb"

# ------------------------
# DICOM Backend (DIMSE target for bridged requests)
#-------------------------
[backends.dicom_pacs]
service = "dicom"
[backends.dicom_pacs.options]
aet = "ORTHANC"
host = "localhost"
port = 4242
local_aet = "HARMONY_SCU"

# ------------------------
# Middleware Types
#-------------------------
[middleware_types.dicomweb_bridge]
module = ""

